### PR TITLE
Update for 1.16.x support.

### PR DESCRIPTION
**Pull request by kfox1111**
/kind bug

1.16 requires the driver to have its mode specified. This updates the deployment to work with 1.16.

```release-note
Updated deployment to work with 1.16.
```

### CODE REVIEW

**Comment by msau42** [comment]
/assign @pohly 
Do we want to have different deployment examples for 1.15 and 1.16?

**Comment by pohly** [comment]
> Do we want to have different deployment examples for 1.15 and 1.16?

Yes, because the driver works with both 1.15 and 1.16. If 1.15 is not supported anymore because inline volumes were alpha there, then the documentation should be updated to reflect that.

**Review by sgandon — APPROVED** [review]
LGTM

**Comment by kfox1111** [comment]
> > Do we want to have different deployment examples for 1.15 and 1.16?
> Yes, because the driver works with both 1.15 and 1.16. If 1.15 is not supported anymore because inline volumes were alpha there, then the documentation should be updated to reflect that.

Added back a working 1.15.

**Pull request merged**
