### PR TITLE
Fixes broken link of contributor cheat sheet

### LINKED ISSUE #22: Broken Link of `contributor cheat sheet` need to fix
## Bug Report

I have observed same kind of issue in various kubernetes-csi project.
this happens because after the localization there are too much modifications done in the various directories.
I have observed same issue in [this ](https://github.com/kubernetes-csi/csi-driver-image-populator/blob/master/CONTRIBUTING.md) page also.

It has one broken link of the `contributes  cheat sheet` which needs to fix.
I will try to look in further csi repo as well and try to fix it as soon as I can

/kind bug
/assign

### PR DESCRIPTION
**Pull request by amolmote**
Signed-off-by: amolmote <amolmote201@gmail.com>
Fixes #22

### CODE REVIEW

**Comment by kfox1111** [comment]
Thanks!

**Comment by amolmote** [comment]
welcome @kfox1111, please give the release note lable as well.

**Comment by kfox1111** [comment]
Wasn't sure how to do that when one isn't required... I think I finally figured it out.

/release-note-none

**Pull request merged**
